#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

rm constant/geometry/boundaryLayer.obj > /dev/null 2>&1

#------------------------------------------------------------------------------
