#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

#runApplication chemkinToFoam \
#    chemkin/grimech30.dat chemkin/thermo30.dat chemkin/transportProperties \
#    constant/reactionsGRI constant/thermo.compressibleGasGRI

#runApplication chemkinToFoam \
#               chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
#               constant/reactionsH2AirOF constant/thermo.compressibleGasH2AirOF


runApplication blockMesh
runApplication checkMesh -allGeometry -allTopology


#runApplication topoSet

#runApplication refineMesh

runApplication setFields

runApplication decomposePar

if isTest "$@"
then
    # Test without chemistry
    foamDictionary constant/chemistryProperties -entry chemistry -set off

    runApplication $(getApplication)

else
    # Run without chemistry until 1500 to let the flow field develop
    #foamDictionary system/controlDict -entry writeInterval -set 1500
    #foamDictionary system/controlDict -entry endTime -set 0.0005
    #foamDictionary constant/chemistryProperties -entry chemistry -set off

    #runApplication $(getApplication)
    runParallel $(getApplication)
    runApplication reconstructPar

    # Run with chemistry until flame reaches its full size
    #foamDictionary system/controlDict -entry writeInterval -set 100

    #foamDictionary system/controlDict -entry endTime -set 0.01
    #foamDictionary constant/chemistryProperties -entry chemistry -set on
    #runApplication -o $(getApplication)
    #runParallel $(getApplication)
    #runApplication reconstructPar

fi

#------------------------------------------------------------------------------
