#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

\rm -rf 0 postProcessing-*
\rm -f *.dat *.png constant/turbulenceProperties
