#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -f ./flange ./*.obj > /dev/null 2>&1

# Remove surface and features
rm -f constant/triSurface/flange.stl.gz > /dev/null 2>&1
rm -f constant/triSurface/flange.eMesh  > /dev/null 2>&1
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1

#------------------------------------------------------------------------------
