#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

rm 0/alpha.water.gz 0/alpha.water 2>/dev/null
rm -rf *Flux

#------------------------------------------------------------------------------
