#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase
rm -fr 0
rm -rf Fieldview > /dev/null 2>&1

#------------------------------------------------------------------------------
