#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

cp -r 0.org 0

runApplication blockMesh
runApplication setFields

cp system/controlDict.org system/controlDict
cp system/fvSchemes.org system/fvSchemes

runApplication $(getApplication)

sed -i 's/endTime         1;/endTime         2;/g' system/controlDict
sed -i 's/Gauss linear corrected;/Gauss harmonic corrected;/g' system/fvSchemes

$(getApplication) > log.laplacianFoam2

sed -i 's/endTime         2;/endTime         3;/g' system/controlDict
sed -i 's/grad(T)         Gauss linear;/grad(T)         Gauss weightedFlux "DT";/g' system/fvSchemes

$(getApplication) > log.laplacianFoam3

runApplication -s singleGraph  postProcess -func singleGraph

gnuplot plot.gnu

#------------------------------------------------------------------------------
