#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=Test-volField

# Compile
runApplication wmake ..

runApplication blockMesh

runApplication $application

#------------------------------------------------------------------------------
