#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

# create mesh
runApplication blockMesh

# Copy 0.org to 0
restore0Dir

# create sets
runApplication topoSet

# create baffles and fields
runApplication createBaffles -overwrite

runApplication $application

#- redistributePar to do decomposition
runParallel redistributePar 3 -decompose -cellDist

#- Continue running for a bit more
runParallel -log log.reactingParcelFoam-par $application 3

#- Reconstruct all times
runParallel -log log.redistributePar-1 redistributePar 3 -reconstruct


# ----------------------------------------------------------------- end-of-file
