#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZonesOnly -overwrite
restore0Dir
runApplication setFields -region water
runApplication $application


#------------------------------------------------------------------------------
