#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/triSurface/blob.stl.gz > /dev/null 2>&1

rm -rf constant/cellAlignments > /dev/null 2>&1
rm -rf constant/targetCellSize > /dev/null 2>&1
rm -rf constant/internalDelaunayVertices > /dev/null 2>&1

(
    cd constant/backgroundMeshDecomposition/polyMesh 2>/dev/null || exit
    rm -f boundary faces neighbour owner points
)

rm -rf snapToSurface?.obj > /dev/null 2>&1
rm -rf tetsToSnapTo.obj > /dev/null 2>&1

#------------------------------------------------------------------------------
