#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove 0.org/ copy and post-processing directories
\rm -rf 0 postProcessing

# remove post-processing directory
rm -rf postProcessing

# copy 0.orig to 0
cp -r 0.orig 0

#------------------------------------------------------------------------------
